config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :categories

  match "/contact" => "about#new", via: "get", as: "contact_new"
  match "/contact" => "about#create", via: "post", as: "contact"
  get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/how-it-works" => "pages#how_it_works"
  get "/faq" => "pages#faq"
  get "/cart" => "cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id/" => "cart#add", as: :add_to_cart
  root "pages#home"
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :require_user

  def add
    product = Product.friendly.find(params[:id])

    session[:cart] ||= {}
    product_id = product.id.to_s

    if session[:cart][product_id]
      session[:cart][product_id] += 1
    else
      session[:cart][product_id] = 1
    end

    redirect_to cart_path
  end

  def clearCart
    session[:cart] = nil
    redirect_to cart_path
  end

  def index

    if session[:cart]
      @cart = session[:cart]
    else
      @cart = {}
    end
  end
end

app/views/cart/index.html.erb
<h2>Your Cart</h2>
<% if @cart.empty? %>
    <h5>Your cart is currently empty</h5>
<% else %>
    <%= link_to "Empty Cart", cart_clear_path %>
<% end %>

<% total = 0 %>

<ul>
  <% @cart.each do |id, qty| %>
      <% product = Product.find_by_id(id) %>
    <li class="prod-cat">
      <%= link_to image_tag(product.image.url(:thumb)), product %>
      <p>Quantity: <%= qty %></p> <%= link_to "Remove Product", cart_path(product), method: :delete, data: { confirm: "Are you sure you want to delete #{product.name}" } %>
    </li>
      <% total += qty * product.price %>
    <% end %>
  <p><strong>Total:</strong> <span class="price"><%= number_to_currency total %></span></p>
</ul>