config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :categories

  match "/contact" => "about#new", via: "get", as: "contact_new"
  match "/contact" => "about#create", via: "post", as: "contact"
  get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/how-it-works" => "pages#how_it_works"
  get "/faq" => "pages#faq"
  get "/cart" => "cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id/" => "cart#add", as: :add_to_cart
  root "pages#home"
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :product_categories
  has_many :products, through: :product_categories
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, except: [:index, :new, :create]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Successfully created #{@category.name}."
      redirect_to products_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "#{@category.name} successfully updated!"
      redirect_to products_path
    else
      render "edit"
    end
  end

  def destroy
    if @category.destroy
      flash[:danger] = "#{@category.name} has been deleted!"
      redirect_to root_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end
end

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

<div class="col-xs-6 col-xs-offset-3">
  <%= form_for @category, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>
      <%= f.submit class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h2 class="text-center">Edit Category</h2>

<%= render "form" %>

app/views/categories/index.html.erb
<h1 class="product text-center">Categories</h1>
<% @categories.each do |category| %>
<ul>
  <div class="well col-md-4 col-md-offset-4">
    <li class="article-title">
      <%= link_to category.name, category_path(category) %>
    </li>
    <li><small>(<%= pluralize category.products.count, "product" %>)</small></li>
  </div>
</ul>
<% end %>

app/views/categories/new.html.erb
<h2 class="text-center">Create Category</h2>

<%= render "form" %>

app/views/categories/show.html.erb
<h2 class="text-center"><%= @category.name %></h2><small>(<%= pluralize @category.products.count, "product" %>)</small>
<div align="center">
  <% if logged_in? && current_user.admin? %>
      <div class="row">
        <%= link_to "Edit Category Name", edit_category_path(@category) %>
      </div>
  <% end %>
</div>

<div class="row">
  <div class="col-xs-12">
    <% if @category.products.size > 0 %>
        <ul>
          <% @category.products.each do |product| %>
          <li class="prod-cat"> <%= link_to product_path(product.friendly_id) do  %>
                <h6><%= product.name %></h6>
                <%= image_tag product.image.url(:thumb) %></li>
            <% end %>
        </ul>
    <% end %>
    <% else %>
        <p class="text-center">No product available for this category</p>
    <% end %>
  </div>
</div>