config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :categories

  match "/contact" => "about#new", via: "get", as: "contact_new"
  match "/contact" => "about#create", via: "post", as: "contact"
  get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/how-it-works" => "pages#how_it_works"
  get "/faq" => "pages#faq"
  get "/cart" => "cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id/" => "cart#add", as: :add_to_cart
  root "pages#home"
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :reviews
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :new, :create]
  before_action :require_admin_user, except: [:index, :show]

  def index
    @products = Product.all.paginate(page: params[:page], per_page: 12)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
        flash[:success] = "You have successfully created #{@product.name}"
        redirect_to products_path
    else
        render "edit"
    end
  end

  def show
    @reviews = Review.where(product_id: @product.id).order("created_at DESC")
    @category = Category.where(params[:id])

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = "#{@product.name} was updated successfully."
      redirect_to product_path(@product)
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "#{@product.name} was deleted!"
      redirect_to products_path
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :retail, :refurbished, category_ids: [])
  end

  def set_product
    @product = Product.friendly.find(params[:id])
  end

  def require_admin_user
    if !current_user.admin?
      flash[:danger] = "Only admins can perform that action"
      redirect_to root_path
    end
  end
end

app/views/products/_form.html.erb
<%= render "shared/errors", obj: @product %>

<div class="col-xs-6 col-xs-offset-3">
    <%= form_for @product, html: { multipart: true } do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control input-lg", autofocus: true %>
        </div>
        <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control input-lg" %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: "form-control input-lg" %>
        </div>
          <div class="form-group">
            <%= f.label :retail %>
            <%= f.text_field :retail, class: "form-control input-lg" %>
          </div>
          <div class="form-group">
            <%= f.label :refurbished %>
            <%= f.text_field :refurbished, class: "form-control input-lg" %>
          </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <div class="row">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <%= cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
          <% end %>
          </div>
        </div>
        <div class="actions">
            <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<h1 class="text-center">Edit product</h1>

<%= render "shared/errors", obj: @product %>

<%= render "form" %>

app/views/products/index.html.erb
<h2 class="text-center">Products</h2>
  <% @products.each do |product| %>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6">
      <div class="thumbnail">
        <%= link_to product_path(product.friendly_id) do  %>
            <%= image_tag product.image.url(:thumb) %>
        <% end %>
        <div class="caption">
          <h3 class="text-center"><span class="prod-title"><%= product.name %></span></h3>
          <hr/>
          <p><%= truncate(product.description, length: 100) %></p>
          <p><%= link_to "Add to Cart", add_to_cart_path(product), class: "btn btn-success-ind" %>&nbsp;<span class="index-price"><%= number_to_currency product.price %></span></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @products, previous_label: "Previous",  next_label: "Next" %>

app/views/products/new.html.erb
<h2 class="product text-center">Create Product</h2>

<%= render "form" %>

app/views/products/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "#{@product.name}", product_path(@product) %></li>
</ol>
<div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
    <%= image_tag @product.image.url(:medium) %>
</div>
<div class="col-lg-6 col-sm-6 col-xs-6">
    <h4><%= @product.name %> <% if @product.refurbished? %> <span class="refurbished">refurbished</span> <% end %></h4>
    <div class="star-rating" data-score= <%= @avg_review %> ></div>

  <p class="description"><%= @product.description %></p>

  <p><strong>Retail:</strong> <span class="crossed-price"><%= number_to_currency @product.retail %></span></p>
  <p class="member"><strong>Member Price:</strong> <span class="price"><%= number_to_currency @product.price %></span> <span class="saving">(<%= ((@product.retail - @product.price) * 100) / @product.retail %>% Savings)</span></p>
</div>
<%= link_to "Add to Cart", add_to_cart_path(@product), class: "button" %>
<% if logged_in? && current_user.admin? %>
    <%= link_to "Edit", edit_product_path(@product), class: "btn btn-default btn-lg" %>
    <%= link_to "Delete", product_path(@product), class: "btn btn-danger btn-lg", method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

<hr/>

<div class="row">
  <div class="col-lg-6 col-md-12 col-xs-12 no-review">
    <% if @reviews.blank? %>
        <h4>No reviews yet. Be the first!</h4>
        <%= link_to new_product_review_path(@product), class: "button-review" do %>
            <i class="fa fa-pencil"></i>
            Write a Review
        <% end %>
    <% else %>
        <h4 class="reviews">Reviews <i class="fa fa-commenting"></i></h4> <span id="review">(<%= pluralize(@reviews.count, "Customer Review") %>)</span>
        <hr/>
        <% @reviews.each do |review| %>
        <div class="review_title">
          <div class="star-rating" data-score="<%= review.rating %>"></div>
          <p><%= review.comment %></p>
          <p class="ago">Reviewed <%= time_ago_in_words(review.created_at) %> ago by <%= "#{review.user.name} #{review.user.last_name[0]}" %>.</p>
          <% if current_user %>
            <% if review.user == current_user || current_user.admin? %>
                <%= link_to "Edit", edit_product_review_path(@product, review), class: "btn btn-xs btn-info" %>
                <%= link_to "Delete", product_review_path(@product, review), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete your review?" } %>
              <% end %>
          <% end %>
        </div>
     <% end %>
            <%= link_to new_product_review_path(@product), class: "button-review" do %>
                <i class="fa fa-pencil"></i>
                Write a Review
            <% end %>
    <% end %>
  </div>
</div>

<script>
  $(".star-rating").raty({
     path: "/assets/",
     readOnly: true,
      score: function() {
          return $(this).attr("data-score");
      }
  });
</script>