config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:new]
  resources :products do
    resources :reviews, except: [:show, :index]
  end

  resources :categories

  match "/contact" => "about#new", via: "get", as: "contact_new"
  match "/contact" => "about#create", via: "post", as: "contact"
  get "/signup" => "users#new"
  get "/login" => "sessions#new"
  post "login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  get "/how-it-works" => "pages#how_it_works"
  get "/faq" => "pages#faq"
  get "/cart" => "cart#index"
  get "/cart/clear" => "cart#clearCart"
  get "/cart/:id/" => "cart#add", as: :add_to_cart
  root "pages#home"
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-6">
      <ul class="footer-nav">
        <li><%= link_to "Contact Us", contact_path %></li>
        <li><%= link_to "How It Works", how_it_works_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <ul class="social-icons">
        <li>
          <%= link_to "http://www.facebook.com" do %>
              <i class="ion-social-facebook"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "https://twitter.com/tinito_sales" do %>
              <i class="ion-social-twitter"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "http://www.googleplus.com" do %>
              <i class="ion-social-googleplus"></i>
          <% end %>
        </li>
        <li>
          <%= link_to "http://www.instagram.com" do %>
              <i class="ion-social-instagram"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <p>
      Copyright &copy; tinito <%= Time.now.strftime("%Y") %>. All rights reserved.
    </p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <span class="logo">
          tinito <i class="fa fa-truck"></i>
            <small>&mdash; Prices that fell off a truck! &reg;</small>
          </span>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
                <li><%= link_to cart_path do %>
                    <i class="glyphicon glyphicon-shopping-cart"></i>
                    <span class="badge">3</span>
                    <% end %>
                </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% Category.all.order("name ASC").each do |category| %>
                    <li><%= link_to "#{category.name}", category_path(category) %> <small>(<%= pluralize category.products.count, "product" %>)</small></li>
                <% end %>
              </ul>
            </li>
            <% if logged_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span> <span class="badge"><%= "Admin" if current_user.admin? %></span></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "View Profile", user_path(current_user) %></li>
                        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                      <% if logged_in? && current_user.admin? %>
                        <li><%= link_to "Create Product", new_product_path %></li>
                        <li><%= link_to "Create Categories", new_category_path %></li>
                      <% end %>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
                <% else %>
                        <li><%= link_to "Log In", login_path %></li>
                     </ul>
                </li>
            <% end %>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tinito&copy;</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: "text/javascript" %>
  <%= javascript_include_tag "application" %>
  <%= tag :meta, name: "stripe_api_key", content: STRIPE_PUBLIC_KEY %>
  <%= favicon_link_tag "favicon.ico" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render "layouts/nav" %>
<div class="container">
    <%= render "layouts/messages" %>
        <%= yield %>
</div>
    <%= render "layouts/footer" %>

</body>
</html>